### ISSUE TITLE
How did you get the historical data?

### ISSUE THREAD

**Issue by dagumak** [tfbsubscribers/tfbsubscribers.github.io#2]
Did you just store it every day and upload it automatically? Is that code open sourced?

**Comment by JJagaimo** [comment]
I wrote a python script that would record the data every couple of seconds and left it running the entire time on my computer. The data is then stored in a json file, and then uploaded to github using a batch file to run a git command. The data comes from the youtube api, provided by google. You'll need to make a project in their thing to acquire a key, and then use that key in the url. They limit the number of requests per hour.

The python script is in[ /Misc ](https://github.com/tfbsubscribers/tfbsubscribers.github.io/blob/master/misc/y.py)and it will record the data, put it into a file, create a commit, then run the batch file (as I had trouble getting python to execute the git command). The timing will be slightly off because each request from the api takes a bit + writing the data to disk, and the 10 minutes was just an estimate of how long it took.

The directories will be a bit weird because the misc folder is a copy of the scripts I had outside of the repository folder and the record data.bat was on the desktop (different hard drive)

It's a bit inefficient, considering 
1. Overwriting entire file every time
2. Storing entire timestamp and stuff when I could have used relative time stamps to shorten the amount of data

but both of those could be fixed with some manipulation.

**Comment by dagumak** [comment]
@JJagaimo Thanks! I appreciate the quick feedback and thorough explanation. I'll check out the script.

**Comment by dagumak** [comment]
By the way, did you ever exceed the quota? How much did you use?

**Comment by JJagaimo** [comment]
I didn't exceed the quota for the script (the quota was pretty high, but I don't remember how much was actually used)

Quotas for the YouTube Data API v3:
50,000,001 per day
300,000 per 100 seconds

I crossed 300,000 on the website when it was really active (for the live updates), so I created a few more projects and made it select randomly from 5 keys.

**Comment by dagumak** [comment]
@JJagaimo nice! Thanks again!
